version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      runas: root

  AfterInstall:
    - location: scripts/configure_nginx.sh
      runas: root

  ApplicationStart:
    - location: scripts/restart_nginx.sh
      runas: root
