version: 0.0
os: linux

files:
  - source: nginx.conf
    destination: /etc/nginx/

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
  AfterInstall:
    - location: scripts/restart_nginx.sh
