version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin 991940085316.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building NGINX image"
      - docker build -t nginx .

  post_build:
    commands:
      - echo "Pushing NGINX image to ECR"
      - docker tag nginx:latest 991940085316.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
      - docker push 991940085316.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
